sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.2.6
  - 2.4.0

env:
  matrix:
    - RAILS='3.2.22.5'
    - RAILS='4.2.8'
    - RAILS='5.0.2'

matrix:
  exclude:
    - env: RAILS='5.0.2'
      rvm: 2.0.0
